name: easy_assets
description: "Easy assets generator using flutter_gen and intl l10n"
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.16
  lottie: ^3.1.3
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  flutter_gen_runner: ^5.8.0


flutter:
  generate: true # Add this line for l10n generation
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/chip3/chip3.jpg
    - assets/images/chip3/chip3.jpg # duplicated
    - assets/images/icons/fuchsia.svg
    - assets/images/icons/kmm.svg
    - assets/images/icons/paint.svg
    - assets/images/icons/dart@test.svg
    - assets/json/
    - assets/lottie/

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway-Italic.ttf
          style: italic
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-Regular.ttf
        - asset: assets/fonts/RobotoMono-Bold.ttf
          weight: 700

    # duplicated
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-Regular.ttf
        - asset: assets/fonts/RobotoMono-Bold.ttf
          weight: 700

