name: easy_assets
description: "Easy assets generator using flutter_gen and intl l10n"
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.16
  lottie: ^3.1.3
  intl: ^0.19.0
  dio: ^5.7.0
  floor: ^1.5.0
  flutter_dotenv: ^5.2.1
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  retrofit: ^4.4.1
  sqflite: ^2.4.1
  path_provider: ^2.1.5
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  flutter_gen_runner: ^5.8.0
  retrofit_generator: ^9.1.5
  json_serializable: ^6.9.0
  floor_generator: ^1.5.0
  freezed: ^2.5.7


flutter:
  generate: true # Add this line for l10n generation
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
    - assets/lottie/
    - assets/sounds/

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway-Italic.ttf
          style: italic
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-Regular.ttf
        - asset: assets/fonts/RobotoMono-Bold.ttf
          weight: 700

    # duplicated
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-Regular.ttf
        - asset: assets/fonts/RobotoMono-Bold.ttf
          weight: 700

